<?php

echo $this->getContent();exit; ?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0">
    <meta name="p:domain_verify" content="dd668c2ae785fae2ea70e66ef33edba7"/>
    <meta name="alexaVerifyID" content="Dmkd6Dz3tVeuJSrnGL0z1Tow6ZY"/>
    <meta name="keywords"
          content="Software Development Company, software development, IT Outsourcing Services, Offshore Software Development, Offshore Outsourcing Services, Outsourced Product Development, Mobile Application Development, Web Design and development, Search Engine Optimization, SEO Services, web design company, web design, node js mobile application, node js development company, mongo nosql">
    <meta name="description"
          content="LinkITes - Software Development Company | IT Outsourcing Services | Outsourced Product Development | Mobile Application Development |  Web Design and Development | Search Engine Optimization | node js development company">
    <meta name="author" content="Linkites">
    <meta name='yandex-verification' content='754464d9b64e5e3b'/>

    <link rel="shortcut icon" href="https://s3.amazonaws.com/linkitesweb/favicon.png">
    <title>LinkITes - Software Development Company | IT Outsourcing Services | Outsourced Product Development | Mobile
        Application Development | Web Design and Development | node js development company</title>

    <!-- LOAD CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/interface.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/css/icons-font.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/masterslider/style/masterslider.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/masterslider/skins/default/style.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/masterslider/skins/designare/style.css" rel='stylesheet' type='text/css' media="screen">
    <link href="assets/css/layout.css" rel="stylesheet" type="text/css" media="screen">

    <!-- SLIDER REVOLUTION 4.x DESIGNARE CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="assets/rs-plugin/css/designare-settings.css" media="screen"/>

    <!-- COLORS -->
    <link href="assets/css/color-variations/decor.css" rel="stylesheet" type="text/css" media="screen" title="linkites">

    <!-- USED FOR RESPONSIVE ADJUSTMENTS -->
    <link href="assets/css/resize.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/css/style.css" rel="stylesheet" type="text/css" media="screen">
    <!-- LOAD GOOGLE FONTS -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:100,300,600,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:600,800' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Load JQuery at this point if you use the Numerical Increments in your page -->
    <script src="assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="assets/js/utils.js" type="text/javascript"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="assets/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="assets/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-38277461-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!--Verification: 754464d9b64e5e3b-->

    <!--popup js -->
    <script src="assets/js/bootstrap.js"></script>
    <!--  <script type="text/javascript">

     $(document).ready(function(){
         $("#myModal").modal('show');
     });
 </script>-->

    <!--end of popup css-->
</head>
<body>
<!--
<div id="myModal" class="modal fade landing_model">
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-content_bg">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title">Meet Us at Gitex - Dubai 18th-22nd Oct</h4>
        </div>
        <div class="modal-body">
            <div class="gitex_img"><img src="https://s3.amazonaws.com/linkitesweb/gitex_poup_logo.png" class="img-responsive"> </div>
            <p class="stand_text">Sheikh Rashid Hall Stand:SR-E10</p>

            <h5>Dubai World Trade Centre</h5>

        </div>
        <div class="modal-footer">

          <a href= "http://www.gitex.com/page.cfm/Action=Exhib/ExhibID=850/loadSearch=372723_7944" target="_blank" class=" btn btn-primary">View More</a>
        </div>
    </div>
    </div>
</div>
</div>
-->


<div id="load"></div>
<div class="everything">
    <!-- BEGIN: HEADER BAR
         OPTIONS: "dark", "style2", "style1", "border" and "hide-on-start"
    -->
    <div class="navbar navbar-default style2 navbar-fixed-top" role="navigation">
        <!-- BEGIN: NAV-CONTAINER -->
        <div class="nav-container">
            <div class="navbar-header">
                <!-- BEGIN: TOGGLE BUTTON (RESPONSIVE)-->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- BEGIN: LOGO -->
                <a class="navbar-brand nav-to" href="index.php">
                    <img class="img-responsive link-logo" src="https://s3.amazonaws.com/linkitesweb/Linkites-logos.png"
                         alt="Linkites: IT Services, Consulting and Business Solutions">
                </a>
            </div>

            <!-- BEGIN: MENU -->

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!--
                 <li class="portfolio_text">
                        MEET US AT
                    </li>
                    <li>
                      <a class="portfolio-page" href="http://www.gitex.com/page.cfm/Action=Exhib/ExhibID=850/loadSearch=372723_7944" target="_blank">
                        <img src="https://s3.amazonaws.com/linkitesweb/gitex_logo.png" alt="Portfolio Page">
                      </a>
                    </li>-->
                    <li><a href="#home">HOME</a></li>
                    <li><a href="#who_we_are">Who we are</a>
                        <ul class="dropdown-menu">
                            <li><a href="#about">About Us</a></li>
                            <li><a href="#featured">Featured Works</a></li>
                            <li><a href="#team">Meet the Team</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-to" href="index.php#what_we_do">What we do</a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-to" href="androiddevelopment.html">Android Development</a></li>
                            <li><a class="nav-to" href="iOSdevelopment.html">iOS Development</a></li>
                            <li><a class="nav-to" href="meteordevelopment.html">Meteor Development</a></li>
                            <li><a class="nav-to" href="nodejsdevelopment.html">Nodejs Development</a></li>
                        </ul>
                    </li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="career.html">Career</a></li>
                    <li><a href="#contacts">Contact</a></li>
                </ul>
            </div>


            <!-- END: MENU -->
        </div>
        <!--END: NAV-CONTAINER -->
    </div>
    <!-- END: HEADER BAR -->

    <section id="moving-text">
        <marquee>

            <span>Latest News:</span>

		<span><i class="fa fa-angle-double-left str-clr"></i>
		Linkites has now started developing iPhone app using latest  IOS Swift to know more, <a
                href="https://developer.apple.com/swift/">click here</a>.</span>

            <!--<span><i class="fa fa-angle-double-left str-clr"></i>
            Job Hirings:Click here for <a href="http://www.linkites.com/career.html">
            Apply Now</a> and check the <a href="http://www.linkites.com/career.html">Interview status</a>.--></span>


        </marquee>
    </section>
    <section id="home" class="nav-boxes">
        <div class="project-slider">
            <div class="project-slider-image">
                <div class=" container numbers-colum">
                    <div class="row for-res">
                        <div class="col-md-2 col-sm-2 clients-no">
                            <p class="number-para-1">
                                <span class="client-figure">15</span>
                                <span class="client-text">Happy</span>
                                <span class="client-text">Clients</span>
                            </p>
                        </div>
                        <div class="col-md-8 col-sm-8 tech-logo-wrapper">
                            <div class="tech-logo">
                                <div class="logo-wrap">
                                    <img class="img-responsive img1 NodeJS"
                                         src="https://s3.amazonaws.com/linkitesweb/Node/node.png" alt="Linkites-images">
                                    <img class="img-responsive img1 AngularJS"
                                         src="https://s3.amazonaws.com/linkitesweb/Angular/angular.png"
                                         alt="Linkites-images">
                                    <img class="img-responsive img1 MeteorJS"
                                         src="https://s3.amazonaws.com/linkitesweb/Meteor/meteor.png"
                                         alt="Linkites-images">
                                    <img class="img-responsive img1 KnockouJS"
                                         src="https://s3.amazonaws.com/linkitesweb/knockout/knockout.png"
                                         alt="Linkites-images">
                                    <img class="img-responsive img1 Ionic"
                                         src="https://s3.amazonaws.com/linkitesweb/ionic/ionic.png"
                                         alt="Linkites-images">
                                    <img class="img-responsive img1 Android"
                                         src="https://s3.amazonaws.com/linkitesweb/Andriod/andriod.png"
                                         alt="Linkites-images">
                                    <img class="img-responsive img1 Ios"
                                         src="https://s3.amazonaws.com/linkitesweb/ios/ios.png" alt="Linkites-images">
                                    <img class="img-responsive img1 Titanium"
                                         src="https://s3.amazonaws.com/linkitesweb/Titanium/Titanium.png"
                                         alt="Linkites-images">
                                </div>
                                <div class="reduce-block">
                                    <p class="taglines">
                                        <span id="tags" style="font-color:black; display:none;"></span>
                                    </p>

                                    <p class="reduce-text">
                                        <span id="typed" style="white-space:pre; display:none;"></span>
                                    </p>
                                </div>
                                <div class="logo-slider">
                                    <ul class="logo-list" id="NodeJS">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Node/node01.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Node/node02.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Node/node03.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Node/node04.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                    <ul class="logo-list" id="AngularJS">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Angular/angular01.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Angular/angular02.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Angular/angular03.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                    <ul class="logo-list" id="MeteorJS">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Meteor/meteor01.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Meteor/meteor02.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                    <ul class="logo-list" id="KnockouJS">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/knockout/knockout01.png"
                                                 alt="Linkites-images"></li>
                                        <!-- <li><img class="img-responsive img2" src="images/node02.png" alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2" src="images/node03.png" alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2" src="images/node04.png" alt="Linkites-images"></li> -->
                                    </ul>

                                    <ul class="logo-list" id="Ionic">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/ionic/ionic01.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                    <ul class="logo-list" id="Android">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Andriod/andriod01.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Andriod/andriod2.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Andriod/andriod3.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Andriod/andriod4.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                    <ul class="logo-list" id="Ios">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/ios/ios01.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/ios/ios02.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/ios/ios03.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/ios/ios04.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                    <ul class="logo-list" id="Titanium">
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Titanium/Titanium01.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Titanium/Titanium.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Titanium/Titanium.png"
                                                 alt="Linkites-images"></li>
                                        <li><img class="img-responsive img2"
                                                 src="https://s3.amazonaws.com/linkitesweb/Titanium/Titanium.png"
                                                 alt="Linkites-images"></li>
                                    </ul>

                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 col-sm-2 project-no">
                            <p class="number-para-2">
                                <span class="Project-figure">25</span>
                                <span class="Project-text succes">Successful</span>
                                <span class="Project-text">Projects</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END REVOLUTION SLIDER -->
    </section>

    <!-- BEGIN: ABOUT SECTION -->
    <section id="who_we_are" class="nav-boxes">

        <!-- BEGIN: GREY SECTION WITH "light-text" TEXT AND "section-arrow-down" -->
        <div class="grey-section dark-text section-arrow-down">

            <!-- BEGIN: CONTAINER -->
            <div class="container">

                <!-- BEGIN: ABOUT TITLE -->
                <div class="section-title row">
                    <h2>WHO <span class="bold">WE</span> ARE</h2>

                    <div class="divider colored"></div>
                </div>
                <!-- END -->

                <div class="row">
                    <!-- BEGIN: ABOUT OUR AGENCY -->
                    <div class="col-xs-12 col-sm-6">
                        <h3>About our Agency</h3>

                        <p>Linkites LLC is an IT company that develops applications of every domain and related services
                            for all size of businesses and individual. It is headquartered at Los Angeles. We provides
                            specialized consulting, design & development services in the mobility space - helping
                            clients build mobile solutions on consumer and enterprise side.</p><br>

                        <p>Our experience & capabilities are to build native solutions for phones and tablets (Android,
                            iOS, Windows Phone...) as well HTML5-based mobile web solutions. And, in all our designs &
                            solutions, UI Design and User Experience (UX) is the core!</p>

                        <div class="space"></div>
                    </div>
                    <!-- END -->

                    <!-- BEGIN: ANIMATED SKILLS BARS -->
                    <div class="col-xs-12 col-sm-6">

                        <h3>We Design &amp; Code</h3>

                        <!-- BEGIN: SKILLS DESIGN -->
                        <div class="col-xs-6 col-sm-6" style="padding-left:0;">

                            <!-- SKILL #01 -->
                            <div id="skillbar-1" class="skillbar clearfix notinview" data-percent="95%">
                                <div class="skillbar-title">
                                    <span>Node.js</span>
                                </div>
                                <div class="skillbar-bar">
                                    <div class="skill-bar-percent" style="background: #33a6ff;"></div>
                                    <div class="pointerval">
                                        <span class="value">85%</span>
                                        <span class="pointer"></span>
                                    </div>
                                </div> <!-- End Skill Bar -->
                            </div>

                            <!-- SKILL #02 -->
                            <div id="skillbar-2" class="skillbar clearfix notinview" data-percent="79%">
                                <div class="skillbar-title">
                                    <span>Ruby on Rail</span>
                                </div>
                                <div class="skillbar-bar">
                                    <div class="skill-bar-percent" style="background: #33a6ff;"></div>
                                    <div class="pointerval">
                                        <span class="value">79%</span>
                                        <span class="pointer"></span>
                                    </div>
                                </div>
                            </div> <!-- End Skill Bar -->

                            <!-- SKILL #03 -->
                            <div id="skillbar-3" class="skillbar clearfix notinview" data-percent="79%">
                                <div class="skillbar-title">
                                    <span>Angular.js</span>
                                </div>
                                <div class="skillbar-bar">
                                    <div class="skill-bar-percent" style="background: #33a6ff;"></div>
                                    <div class="pointerval">
                                        <span class="value">39%</span>
                                        <span class="pointer"></span>
                                    </div>
                                </div>
                            </div> <!-- End Skill Bar -->
                        </div>
                        <!-- END: SKILLS DESIGN -->

                        <!-- BEGIN: SKILLS CODE -->
                        <div class="col-xs-6 col-sm-6">

                            <!-- SKILL #01 -->
                            <div id="skillbar-4" class="skillbar clearfix notinview" data-percent="92%">
                                <div class="skillbar-title">
                                    <span>Mobile App Development</span>
                                </div>
                                <div class="skillbar-bar">
                                    <div class="skill-bar-percent" style="background: #1886f4;"></div>
                                    <div class="pointerval">
                                        <span class="value">92%</span>
                                        <span class="pointer"></span>
                                    </div>
                                </div>
                            </div> <!-- End Skill Bar -->

                            <!-- SKILL #02 -->
                            <div id="skillbar-5" class="skillbar clearfix notinview" data-percent="89%">
                                <div class="skillbar-title">
                                    <span>Interface Design | UX</span>
                                </div>
                                <div class="skillbar-bar">
                                    <div class="skill-bar-percent" style="background: #1886f4;"></div>
                                    <div class="pointerval">
                                        <span class="value">89%</span>
                                        <span class="pointer"></span>
                                    </div>
                                </div>
                            </div> <!-- End Skill Bar -->

                            <!-- SKILL #03 -->
                            <div id="skillbar-6" class="skillbar clearfix notinview" data-percent="49%">
                                <div class="skillbar-title"><span>SEO &amp; SMM</span></div>
                                <div class="skillbar-bar">
                                    <div class="skill-bar-percent" style="background: #1886f4;"></div>
                                    <div class="pointerval">
                                        <span class="value">49%</span>
                                        <span class="pointer"></span>
                                    </div>
                                </div>
                            </div> <!-- End Skill Bar -->
                        </div>
                        <!-- END: SKILLS CODE -->

                        <!--
                        <div class="light">
                            <div id="office-slider" class="flexslider">
                                <ul class="slides">
                                    <li>
                                        <img src="images/office/of1.jpg" alt=""/>
                                    </li>
                                    <li>
                                        <img src="images/office/of2.jpg" alt=""/>
                                    </li>
                                    <li>
                                        <img src="images/office/of3.jpg" alt=""/>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        -->
                    </div>
                    <!-- END: ANIMATED SKILLS BARS -->
                </div>
                <!-- END: ROW -->

                <div class="divider-contents"></div>
                <div class="space"></div>

                <div class="row">
                    <!-- BEGIN 4 COLUMNS / 12 COLUMNS (<768px) -->
                    <div class="col-xs-12 col-sm-4">

                        <!-- BEGIN: AGENCY FACTS -->
                        <div id="agency-slider" class="flexslider">
                            <ul class="slides">

                                <!-- SLIDE #01 -->
                                <li>
                                    <div class="big-icon">
                                        <i class="fa fa-clock-o"></i>

                                        <div class="number">3289<span class="unit">h</span></div>
                                        <p>This is the total of hours that we expend design and coding stuff.</p>
                                    </div>
                                </li>

                                <!-- SLIDE #02 -->
                                <li>
                                    <div class="big-icon">
                                        <i class="fa fa-desktop" style="font-size:80px;"></i>

                                        <div class="number">340<span class="unit">Works</span></div>
                                        <p></p>
                                    </div>
                                </li>

                                <!-- SLIDE #03 -->
                                <li>
                                    <div class="big-icon">
                                        <i class="fa fa-facebook"></i>

                                        <div class="number">2444<span class="unit">Fans</span></div>
                                        <p>People who follow us and like our work on facebook</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- END: AGENCY FACTS -->
                    </div>

                    <!-- BEGIN 4 COLUMNS / 12 COLUMNS (<768px) -->
                    <div class="col-xs-12 col-sm-4">
                        <h4>We <i class="fa fa-heart"></i> our Clients</h4>

                        <p>And it’s true. We mean it. We love all of our clients in that wholesome, totally non-creepy
                            sort of way that’s conducive to a healthy, professional relationship! Always heading to
                            build a long term mutual beneficial relationship!</p>
                    </div>

                    <!-- BEGIN 4 COLUMNS / 12 COLUMNS (<768px) -->
                    <div class="col-xs-12 col-sm-4">
                        <h4>Our Methodology</h4>

                        <p>With outsourced work being such a huge gamble for organizations, finding the perfect
                            developer can sometimes feel like finding gold in your cereal – those who have it can’t
                            believe their luck and those who don’t, want it at any cost.</p>
                    </div>
                </div>
                <!-- END ROW -->
            </div>
            <!-- END CONTAINER -->
        </div>
        <!-- END: GREY SECTION -->

        <!-- BEGIN: FEATURED WORKS "light-section" WITH "nopaddingbottom" AND "dark-text" TEXT -->
        <div id="featured" class="light-section nopaddingbottom dark-text">

            <!-- BEGIN: TITLE STYLE 1 -->
            <div class="container section-title">
                <h2>FEATURED <span class="bold">WORKS</span></h2>

                <div class="divider colored"></div>
                <h6 class="text-center">We love blending creativity and simplicity into our products. <a
                        href="#portfolio">View our Portfolio <i class="fa fa-arrow-circle-o-down"></i></a></h6>
            </div>

            <!-- BEGIN: FEATURED WORKS SHOWCASE -->
            <div class="ms-showcase1">
                <!-- Master slider Showcase -->
                <div class="master-slider ms-skin-light-6" id="masterslider-showcase">

                    <!-- SLIDE #01 -->
                    <div class="ms-slide" style="background-color: #fff;">
                        <img id="fetr-wrk1" class="one-img" src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/featured-works/1.png" alt="reality la"/>

                        <h4 class="ms-layer heading-border" style="left:810px; top:90px; bottom: 364px;"
                            data-effect="left(100)"
                            data-delay="0"
                            data-ease="easeOutQuad"
                        >Reality LA</h4>

                        <p class="ms-layer" style="left:810px; top:140px;"
                           data-effect="left(100)"
                           data-delay="100"
                           data-ease="easeOutQuad"
                        >Fishermenlabs wanted a revamp and rebuild of their<br> product &ndash; Realityla.com, the focus
                            was on requirements<br> for consumer branding.<a href="http://realityla.com/"
                                                                             class="nav-to">View Project <i
                                    class="fa fa-arrow-circle-o-right"></i></a></p>

                        <div class="ms-layer" style="left:580px; top:275px;"
                             data-delay="300"
                             data-type="hotspot"
                             data-align="left"
                        >
                            <div class="product-tt"><h3>Payment Gateway</h3>To make the payment secure and on smooth
                                fast-pace used Braintree Payment gateway.
                            </div>
                        </div>

                        <div class="ms-layer" style="left:725px; top:330px;"
                             data-delay="400"
                             data-type="hotspot"
                             data-align="right"
                        >
                            <div class="product-tt"><h3>Custom CMS</h3>Content was the key in Reality LA. So we decided
                                the option of custom CMS for quick content management.
                            </div>
                        </div>

                        <div class="ms-layer" style="left:450px; top:120px;"
                             data-delay="500"
                             data-type="hotspot"
                             data-align="bottom"
                        >
                            <div class="product-tt"><h3>Framework</h3>Worked from scratched front-end using
                                Bootstrap/jQuery frameworks and Ruby on Rails Gems.
                            </div>
                        </div>
                    </div>

                    <!-- SLIDE #02 -->
                    <div class="ms-slide" style="background-color: #fff;">
                        <img src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/featured-works/2.png"
                             alt="discover hawaii tours"/>

                        <h4 class="ms-layer heading-border" style="left:980px; top:90px;width:214px;"
                            data-effect="left(100)"
                            data-delay="0"
                            data-ease="easeOutQuad"
                        >Discover Hawaii Tours</h4>

                        <p class="ms-layer" style="left:980px; top:136px;"
                           data-effect="left(100)"
                           data-delay="100"
                           data-ease="easeOutQuad"
                        >Discover hawai tours
                            At Discover Hawai tours
                            .<br> We take your trip personally and<br> want to fell at home in island
                            <a href="http://www.discoverhawaiitours.com/" class="nav-to">View Project <i
                                    class="fa fa-arrow-circle-o-right"></i></a></p>

                        <div class="ms-layer" style="left:305px; top:335px;"
                             data-delay="100"
                             data-type="hotspot"
                             data-align="top"
                        >
                            <div class="product-tt">
                                <h3></h3>Safe and Secure Shopping
                            </div>
                        </div>

                        <div class="ms-layer" style="left:950px; top:350px;"
                             data-delay="200"
                             data-type="hotspot"
                             data-align="right"
                        >
                            <div class="product-tt">
                                <h3>Framework</h3>
                                Developed in word press
                                and My Sql as Database
                            </div>
                        </div>

                        <div class="ms-layer" style="left:400px; top:150px;"
                             data-delay="300"
                             data-type="hotspot"
                             data-align="bottom"
                        >
                            <div class="product-tt">
                                <h3>Available for Mobiles</h3>
                                Available on Apple and Google play store
                            </div>
                        </div>
                    </div>

                    <!-- SLIDE #03 -->
                    <div class="ms-slide" style="background-color: #fff;">
                        <img src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/featured-works/3.png" alt="Joust"/>

                        <h4 class="ms-layer heading-border" style="left:980px; top:90px;width:128px;"
                            data-effect="left(100)"
                            data-delay="0"
                            data-ease="easeOutQuad"
                        >Joust</h4>

                        <p class="ms-layer" style="left:980px; top:139px;"
                           data-effect="left(100)"
                           data-delay="100"
                           data-ease="easeOutQuad"
                        >Joust is all about making predictions <br>and compeletes in contest on your<br>
                            favorite stuff. <a href="http://www.joust.com/" class="nav-to">View Project <i
                                    class="fa fa-arrow-circle-o-right"></i></a>

                        </p>

                        <div class="ms-layer" style="left:150px; top:280px;"
                             data-effect="left(100)"
                             data-delay="200"
                             data-ease="easeOutQuad">

                            <!--<a href="proj-noajax.html" class="p-button colored">View Details</a>-->
                        </div>

                        <div class="ms-layer" style="left:620px; top:215px;"
                             data-delay="300"
                             data-type="hotspot"
                             data-align="left"
                        >
                            <div class="product-tt"><h3>Framework</h3>
                                Front End developed using
                                Bootstrap3, JavaScript and
                                Angular.js
                            </div>
                        </div>

                        <!-- <div class="ms-layer" style="left:1130px; top:120px;"
                            data-delay="400"
                            data-type="hotspot"
                            data-align="right"
                        >
                            <div class="product-tt"><h3>Multi Demos Available</h3>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</div>
                        </div>-->

                        <div class="ms-layer" style="left:375px; top:110px;"
                             data-delay="400"
                             data-type="hotspot"
                             data-align="right"
                        >
                            <div class="product-tt"><h3>Responsive</h3>
                                Whole App is web Based
                                and
                                responsive to all browser and
                                devices
                            </div>
                        </div>
                    </div>

                    <!-- SLIDE #04 -->
                    <div class="ms-slide" style="background-color: #fff;">
                        <img src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/featured-works/4.png" alt="Realtalk"/>

                        <h4 class="ms-layer heading-border" style="left:1000px; top:50px;width:128px;"
                            data-effect="left(100)"
                            data-delay="0"
                            data-ease="easeOutQuad">SBG App</h4>

                        <p class="ms-layer" style="left:1000px; top:90px;"
                           data-effect="left(100)"
                           data-delay="100"
                           data-ease="easeOutQuad"
                        >
                            SBG –
                            Sociedade Brasileira de<br> Glaucoma is
                            provide inform
                            ation about events,<br> Lessons, case studies etc.
                            <a href="http://www.sbglaucoma.com.br/" class="nav-to">View Project <i
                                    class="fa fa-arrow-circle-o-right"></i></a></p>

                        <!-- <div class="ms-layer" style="left:305px; top:335px;"
                             data-delay="100"
                             data-type="hotspot"
                             data-align="top"
                         >
                             <div class="product-tt"><h3>RESPONSIVE DESIGN</h3>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</div>
                         </div>-->

                        <div class="ms-layer" style="left:950px; top:350px;"
                             data-delay="200"
                             data-type="hotspot"
                             data-align="right"
                        >
                            <div class="product-tt"><h3>Responsive</h3>
                                App is web Based and Mobile
                                Based and responsive to all
                                browser and devices.
                            </div>
                        </div>

                        <div class="ms-layer" style="left:400px; top:150px;"
                             data-delay="300"
                             data-type="hotspot"
                             data-align="bottom"
                        >
                            <div class="product-tt"><h3>Framework</h3>
                                Developed in Ionic, Cardova,
                                HTML, Angular Js and Mango DB.
                            </div>
                        </div>
                    </div>

                    <!-- SLIDE #05 -->
                    <div class="ms-slide" style="background-color: #fff;">
                        <img src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/featured-works/5.png" alt=""/>

                        <h4 class="ms-layer heading-border" style="left:1020px; top:90px;width:128px;"
                            data-effect="left(100)"
                            data-delay="0"
                            data-ease="easeOutQuad">Realtalk</h4>

                        <p class="ms-layer" style="left:1020px; top:136px;"
                           data-effect="left(100)"
                           data-delay="100"
                           data-ease="easeOutQuad"
                        >
                            Real Talk Mobile App help <br>user to chat using custom emoji’s<br>
                            <a href="http://www.realtalkapp.com/" class="nav-to">View Project <i
                                    class="fa fa-arrow-circle-o-right"></i></a></p>

                        <div class="ms-layer" style="left:305px; top:335px;"
                             data-delay="100"
                             data-type="hotspot"
                             data-align="top"
                        >
                            <div class="product-tt"><h3></h3>Play with Emojis</div>
                        </div>

                        <div class="ms-layer" style="left:950px; top:350px;"
                             data-delay="200"
                             data-type="hotspot"
                             data-align="right"
                        >
                            <div class="product-tt"><h3></h3>Developed For iOS and Android
                                i.e. with
                                Android, Objective C,
                                Mango DB and AWS Hosting
                            </div>
                        </div>

                        <div class="ms-layer" style="left:400px; top:150px;"
                             data-delay="300"
                             data-type="hotspot"
                             data-align="bottom"
                        >
                            <div class="product-tt"><h3></h3>Very cool concept and Emojis</div>
                        </div>
                    </div>


                    <!-- SLIDE #06 -->
                    <div class="ms-slide" style="background-color: #fff;">
                        <img src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/featured-works/6.png" alt="Glance"/>

                        <h4 class="ms-layer heading-border" style="left:1040px; top:90px;"
                            data-effect="left(100)"
                            data-delay="0"
                            data-ease="easeOutQuad">Glance</h4>

                        <p class="ms-layer" style="left:1040px; top:136px;"
                           data-effect="left(100)"
                           data-delay="100"
                           data-ease="easeOutQuad"
                        >
                            Talking about modern <br>world, Image, Photos? Talk ab
                            out glance it’s fast,<br> fun and Beautiful
                            <a href="http://www.getglance.com/" class="nav-to">View Project <i
                                    class="fa fa-arrow-circle-o-right"></i></a></p>
                        <!--  <div class="ms-layer" style="left:305px; top:335px;"
                              data-delay="100"
                              data-type="hotspot"
                              data-align="top"
                          >
                              <div class="product-tt"><h3>RESPONSIVE DESIGN</h3>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</div>
                          </div>-->

                        <div class="ms-layer" style="left:950px; top:350px;"
                             data-delay="200"
                             data-type="hotspot"
                             data-align="right"
                        >

                            <div class="product-tt">
                                <h3>Frame work</h3>
                                Node.Js Backend and
                                services and AWS web
                                services
                            </div>
                        </div>

                        <div class="ms-layer" style="left:400px; top:150px;"
                             data-delay="300"
                             data-type="hotspot"
                             data-align="bottom"
                        >
                            <div class="product-tt"><h3></h3>
                                Also Developed in Objective
                                C and Available on Apple
                                Store
                            </div>
                        </div>
                    </div>

                </div>
                <!-- end of masterslider -->
            </div>
            <!-- END: FEATURED WORKS SHOWCASE -->
        </div>
        <!-- END: FEATURED WORKS -->


        <!-- START: PARALLAX - PROCESS ICONS -->
        <div id="parallax-1" class="parallax"
             style="background-image: url(https://s3.amazonaws.com/linkitesweb/parallax/process.jpg);text-align:center;">
            <div class="box-overlay-pattern">

                <!-- Remove this line "overlay-pattern" if you don't want the overlay pattern -->
                <div class="overlay-pattern"></div>

                <!-- BEGIN: PARALLAX CONTENTS -->
                <div class="parallax-content light-text">

                    <!-- TITLE STYLE 1 -->
                    <div class="section-title">
                        <h2>Our Process is simple</h2>

                        <div class="divider-small">
                            <div class="divider colored"></div>
                        </div>
                    </div>

                    <!-- BEGIN: ICONS BORDER HOVER | options "dark-bg", "light-bg", "light-bg border" -->
                    <section id="set-1" class="dark-bg">

                        <!-- Set 1a or 1b for effects on hover "hi-icon-effect-1a" -->
                        <div class="hi-icon-wrap hi-icon-effect-1 hi-icon-effect-1a">

                            <!-- PROCESS ICON #01 -->
                            <div class="hi-icon animated fadeInUp">
                                <!-- Icon here -->
                                <i class="fa fa-search"></i>
                                <!-- Description Tooltip here -->
                                <div class="tooltip-desc">
                                    <span class="tooltip-arrow-down"></span>

                                    <div class="tooltip-content">
                                        <p>We focus on gathering all necessary data which is important for a project to
                                            be successful.</p>
                                    </div>
                                </div>
                                <h6>Research</h6>
                            </div>

                            <!-- PROCESS ICON #02 -->
                            <div class="hi-icon animated fadeInUp delay-200">
                                <i class="fa fa-compass"></i>

                                <div class="tooltip-desc">
                                    <span class="tooltip-arrow-down"></span>

                                    <div class="tooltip-content">
                                        <ul>
                                            <li><i class="fa fa-check-circle-o"></i> Concept - Analysis of the business
                                                need
                                            </li>
                                            <li><i class="fa fa-check-circle-o"></i> Definition of project scope</li>
                                            <li><i class="fa fa-check-circle-o"></i> Evaluation of technical
                                                alternatives
                                            </li>
                                            <li><i class="fa fa-check-circle-o"></i> Formation of the project
                                                acquisition strategy
                                            </li>
                                            <li><i class="fa fa-check-circle-o"></i> Approval of project costs and
                                                obtaining of project funding
                                            </li>
                                            <li><i class="fa fa-check-circle-o"></i> Definition of planning roles and
                                                responsibilities
                                            </li>
                                            <li><i class="fa fa-check-circle-o"></i> Development of the initial Work
                                                Breakdown Structure
                                            </li>
                                            <li><i class="fa fa-check-circle-o"></i> Approval to progress to the design
                                                phase
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <h6>Concept</h6>
                            </div>

                            <!-- PROCESS ICON #03 -->
                            <div class="hi-icon animated fadeInUp delay-400">
                                <i class="fa fa-desktop"></i>

                                <div class="tooltip-desc">
                                    <span class="tooltip-arrow-down"></span>

                                    <div class="tooltip-content">
                                        <p>We consider design stage to take as its initial input the requirements
                                            identified in the approved requirements document. For each requirement, a
                                            set of one or more design elements will be produced as a result of
                                            interviews, workshops, and/or prototype efforts.</p>
                                    </div>
                                </div>
                                <h6>Design</h6>
                            </div>

                            <!-- PROCESS ICON #04 -->
                            <div class="hi-icon animated fadeInUp delay-600">
                                <i class="fa fa-code"></i>

                                <div class="tooltip-desc">
                                    <span class="tooltip-arrow-down"></span>

                                    <div class="tooltip-content">
                                        <p>We follow Agile development using Git so that developers can work
                                            independently of each other before trying to merge their work with the work
                                            of others.</p>
                                    </div>
                                </div>
                                <h6>Development</h6>
                            </div>

                            <!-- PROCESS ICON #05 -->
                            <div class="hi-icon animated fadeInUp delay-800">
                                <i class="fa fa-rocket"></i>

                                <div class="tooltip-desc">
                                    <span class="tooltip-arrow-down"></span>

                                    <div class="tooltip-content">
                                        <p>We use two Deploy environment i.e testing/dev and Production. All the work
                                            should first push on dev environment and after testing we use to push on
                                            production server.</p>
                                    </div>
                                </div>
                                <h6>Deploy</h6>
                            </div>

                            <!-- PROCESS ICON #06 -->
                            <div class="hi-icon animated fadeInUp delay-1000">
                                <i class="fa fa-bullhorn"></i>

                                <div class="tooltip-desc">
                                    <span class="tooltip-arrow-down"></span>

                                    <div class="tooltip-content">
                                        <p>The deployment of the system includes changes and enhancements. We follow
                                            Project management tool which will be last long for any future and
                                            maintenance work.</p>
                                    </div>
                                </div>
                                <h6>Maintenance</h6>
                            </div>
                        </div>
                        <!-- End hi-icon-wrap -->
                    </section>
                    <!-- END: ICONS BORDER HOVER -->
                </div>
                <!-- END: PARALLAX CONTENTS -->
            </div>
            <!-- END box-overlay-pattern -->
        </div>
        <!-- END: PARALLAX -->


        <!-- BEGIN: TEAM MEMBERS "grey-section" WITH "no-after-arrow", "nopaddingbottom" AND "dark-text" TEXT -->
        <div id="team" class="grey-section no-after-arrow nopaddingbottom dark-text">
            <!-- TITLE STYLE 1 -->
            <div class="container">
                <div class="section-title smallmargin">
                    <h2>MEET THE <span class="bold">TEAM</span></h2>

                    <div class="divider colored"></div>
                </div>
            </div>

            <!-- BEGIN: TEAM SHOWCASE -->
            <div class="ms-staff-carousel ms-round">
                <!-- Master slider Team Showcase -->
                <div class="master-slider" id="master-team">

                    <!-- TEAM MEMBER #01 | CENTER DESCRIPTION-->
                    <div class="ms-slide">

                        <!-- Image for Team Member here -->
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/1.jpg"
                             alt="Saket Dandotia"/>

                        <!-- Description of team member here -->
                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Saket Dandotia</span></h3>
                            <h4>Co-Founder &amp; VC &ndash; Sales</h4>

                            <p>Saket has worked as a consultant for Warner Bros., Myffers, Intlfaces and Fox. He
                                believes that sound product strategies make a business grow. His strong knowledge base
                                on technologies around has helped many old or new product start-ups to excel into the
                                right direction. His valuable inputs on project management always help the team.</p>

                            <!-- Colored Social Icons -->
                            <!--div class="socialdiv colored">
                                <ul>
                                    <li><a class="facebook" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Facebook"></a></li>
                                    <li><a class="twitter" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Twitter"></a></li>
                                    <li><a class="forrst" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Forrst"></a></li>
                                    <li><a class="pinterest" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Pinterest"></a></li>
                                    <li><a class="dribbble" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Dribbble"></a></li>
                                    <li><a class="vimeo" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Vimeo"></a></li>
                                </ul>
                            </div-->
                            <!-- end icons -->
                        </div>
                        <!-- end description -->
                    </div>

                    <!-- TEAM MEMBER #02 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/2.jpg"
                             alt="Jitendra Shakyawar"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Jitendra Shakyawar</span></h3>
                            <h4>CTO &amp; Director &ndash; Web Development </h4>

                            <p>Almost 10+ years of work experience in development, team handling and consulting, and
                                very strong learning skills keeps Jitendra updated with new technologies every time.</p>

                            <div class="space"></div>
                            <!-- Glyphicons Social Icons
                            <a href="" class="social linked_in"></a>
                            <a href="" class="social forrst"></a>
                            <a href="" class="social pinboard"></a>
                            <a href="" class="social behance"></a>
                            <a href="" class="social github"></a>-->
                        </div>
                    </div>

                    <!-- TEAM MEMBER #03 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/3.jpg"
                             alt="Virendra Chouhan"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Virendra Chouhan</span></h3>
                            <h4>CTO &amp; Director &ndash; Web Development</h4>

                            <p>Virendra started his career with ASP.NET/C#, is now heading a diverse team on key
                                languages of development. With 8+ years of work experience Virendra is currently focused
                                on Node.js which he enjoys a lot.</p>

                            <div class="space"></div>
                            <!-- Glyphicons Social Icons
                            <a href="" class="social linked_in"></a>
                            <a href="" class="social forrst"></a>
                            <a href="" class="social pinboard"></a>
                            <a href="" class="social behance"></a>
                            <a href="" class="social github"></a>-->
                        </div>
                    </div>

                    <!-- TEAM MEMBER #04 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/4.jpg"
                             alt="Alok Patil"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Alok Patil</span></h3>
                            <h4>Co-Founder &amp; Solution Architect</h4>

                            <p>Alok for his depth knowledge and working on multiple technologies at a time, is also
                                popular as <i>machine</i> among mates. Besides directing product development on iOS and
                                Android, he has himself developed some awesome applications in Node.js and Javascript.
                                Alok has got 8+ years of experience and have provided consultancy to Catapult Inc.,
                                Intlfaces, Fishermenlabs and Myffers.</p>

                            <div class="space"></div>
                            <!-- Glyphicons Social Icons
                            <a href="" class="social linked_in"></a>
                            <a href="" class="social forrst"></a>
                            <a href="" class="social pinboard"></a>
                            <a href="" class="social behance"></a>
                            <a href="" class="social github"></a>-->
                        </div>
                    </div>

                    <!-- TEAM MEMBER #05 | LEFT DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/5.jpg"
                             alt="Sonal Khandelwal"/>

                        <div class="ms-info container left-desc">
                            <div class="contents-left">
                                <h3><span class="bold">Sonal</span> Khandelwal</h3>
                                <h4>Manager &ndash; Client Relationship</h4>
                            </div>

                            <div class="contents-right">
                                <h5>The Big Boss <i class="fa fa-smile-o"></i></h5>

                                <p>After working in a top level MNC and taking a Master Degree of Management, Sonal is
                                    well equipped with Relationship Management skills and she is the best in it.</p>

                                <!--div class="socialdiv colored">
                                    <ul>
                                        <li><a class="facebook" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Facebook"></a></li>
                                        <li><a class="twitter" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Twitter"></a></li>
                                        <li><a class="forrst" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Forrst"></a></li>
                                        <li><a class="pinterest" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Pinterest"></a></li>
                                        <li><a class="dribbble" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Dribbble"></a></li>
                                        <li><a class="vimeo" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Vimeo"></a></li>
                                    </ul>
                                </div-->
                            </div>
                        </div>
                    </div>

                    <!-- TEAM MEMBER #04 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif"
                             data-src="https://s3.amazonaws.com/linkitesweb/team/harish.JPG" alt="Harish Chouhan"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Harish Chouhan</span></h3>
                            <h4>Team Lead &ndash; iOS</h4>

                            <p>Harish having 8+ years on iOS development he has work with Fortune 500 companies in the
                                past. When it comes to iOS apps and Linkites Harish is there to make your idea into
                                reality.</p>

                            <div class="space"></div>
                            <!-- Glyphicons Social Icons
                            <a href="" class="social linked_in"></a>
                            <a href="" class="social forrst"></a>
                            <a href="" class="social pinboard"></a>
                            <a href="" class="social behance"></a>
                            <a href="" class="social github"></a>-->
                        </div>
                    </div>
                    <!-- TEAM MEMBER #05 | LEFT DESCRIPTION-->

                    <!-- TEAM MEMBER #06 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/5a.jpg"
                             alt="Dharmanshu Sharma"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Dharmanshu</span> Sharma</h3>
                            <h4>Director &ndash; Marketing</h4>

                            <p>Dharmanshu has worked with ICICI &amp; HDFC bank and his intense knowledge of Sales and
                                Marketing very helpful in formulating strategies require to grow a company.</p>

                            <!--div class="socialdiv colored">
                                <ul>
                                    <li><a class="facebook" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Facebook"></a></li>
                                    <li><a class="twitter" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Twitter"></a></li>
                                    <li><a class="forrst" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Forrst"></a></li>
                                    <li><a class="pinterest" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Pinterest"></a></li>
                                    <li><a class="dribbble" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Dribbble"></a></li>
                                    <li><a class="vimeo" href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Vimeo"></a></li>
                                </ul>
                            </div-->
                        </div>
                    </div>

                    <!-- TEAM MEMBER #07 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/5b.jpg"
                             alt="Sonu Parmar"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Sonu</span> Parmar</h3>
                            <h4>Director &ndash; Marketing</h4>

                            <p></p>

                            <div class="space"></div>
                            <!-- Glyphicons Social Icons
                            <a href="" class="social linked_in"></a>
                            <a href="" class="social forrst"></a>
                            <a href="" class="social pinboard"></a>
                            <a href="" class="social behance"></a>
                            <a href="" class="social github"></a>-->
                        </div>
                    </div>

                    <!-- TEAM MEMBER #11 | CENTER DESCRIPTION-->
                    <div class="ms-slide">
                        <img src="masterslider/blank.gif" data-src="https://s3.amazonaws.com/linkitesweb/team/nitin.png"
                             alt="Anjali Gupta"/>

                        <div class="ms-info container center-desc">
                            <h3><span class="bold">Nitin</span> Khotiwale</h3>
                            <h4>Team Lead - PHP</h4>

                            <p>Nitin having 6+ years of work experience in php. he is depth knowledge in CMS, Shoping
                                cart and frameworks. now he is heandling a php projects and team.</p>

                            <div class="space"></div>
                            <!-- Glyphicons Social Icons
                            <a href="https://www.facebook.com/profile.php?id=100000678146723" class="social facebook"></a>-->
                        </div>
                    </div>

                </div>
                <!-- End Master slider Team Showcase -->
                <div class="ms-staff-info" id="staff-info"></div>
            </div>
            <!-- END: TEAM SHOWCASE -->


            <!-- BEGIN: COLORED SECTION -->
            <div class="colored-section">
                <h2 class="no-margin">You can trust us. We are an experienced Team.</h2>
            </div>

            <!-- BEGIN: NUMERICAL INCREMENT -->
            <div class="container numerical-c">
                <div class="row">
                    <!-- BEGIN 3 COLUMNS / 6 COLUMNS (<768px)
                         Numerical #01 -->
                    <div class="col-xs-6 col-sm-3 animated fadeInUp">

                        <!-- Center Icon here -->
                        <div class="center-icon" style="">
                            <i class="fa fa-clock-o"></i>
                        </div>

                        <!-- Numerical here -->
                        <div>
                            <div class="numericals">
                                <!-- Numerical script -->
                                <script type="text/javascript">
                                    jQuery(window).load(function () {
                                        if (isScrolledIntoView("numerical-10")) {
                                            jQuery('#numerical-10').removeClass('notinview');
                                            incrementNumerical('#numerical-10', 3289, 100);
                                        }
                                    });
                                    jQuery(window).scroll(function () {
                                        if (jQuery('#numerical-10.notinview').length) {
                                            if (isScrolledIntoView("numerical-10")) {
                                                jQuery('#numerical-10').removeClass('notinview');
                                                incrementNumerical('#numerical-10', 3289, 100);
                                            }
                                        }
                                    });
                                </script>

                                <!-- Numerical html -->
                                <div class="numerical-container">
                                    <div id="numerical-10" class="notinview">
                                        <div class="value">0</div>
                                        <div style="font-size:20;" class="unit"></div>
                                    </div>
                                    <div class="numerical-content">Hours of work</div>
                                </div>
                            </div>
                        </div>
                        <!-- End Numerical -->
                    </div>

                    <!-- Numerical #02 -->
                    <div class="col-xs-6 col-sm-3 animated fadeInUp delay-200">
                        <div class="center-icon" style="">
                            <i class="fa fa-desktop"></i>
                        </div>
                        <div>
                            <div class="numericals">
                                <script type="text/javascript">
                                    jQuery(window).load(function () {
                                        if (isScrolledIntoView("numerical-12")) {
                                            jQuery('#numerical-12').removeClass('notinview');
                                            incrementNumerical('#numerical-12', 340, 5);
                                        }
                                    });
                                    jQuery(window).scroll(function () {
                                        if (jQuery('#numerical-12.notinview').length) {
                                            if (isScrolledIntoView("numerical-12")) {
                                                jQuery('#numerical-12').removeClass('notinview');
                                                incrementNumerical('#numerical-12', 340, 5);
                                            }
                                        }
                                    });
                                </script>
                                <div class="numerical-container">
                                    <div id="numerical-12" class="notinview">
                                        <div class="value">0</div>
                                        <div style="font-size:20;" class="unit"></div>
                                    </div>
                                    <div class="numerical-content">Finished Works</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Numerical #03 -->
                    <div class="col-xs-6 col-sm-3 animated fadeInUp delay-400">
                        <div class="center-icon" style="">
                            <i class="fa fa-user"></i>
                        </div>
                        <div>
                            <div class="numericals">
                                <script type="text/javascript">
                                    jQuery(window).load(function () {
                                        if (isScrolledIntoView("numerical-13")) {
                                            jQuery('#numerical-13').removeClass('notinview');
                                            incrementNumerical('#numerical-13', 95, 5);
                                        }
                                    });
                                    jQuery(window).scroll(function () {
                                        if (jQuery('#numerical-13.notinview').length) {
                                            if (isScrolledIntoView("numerical-13")) {
                                                jQuery('#numerical-13').removeClass('notinview');
                                                incrementNumerical('#numerical-13', 95, 5);
                                            }
                                        }
                                    });
                                </script>
                                <div class="numerical-container">
                                    <div id="numerical-13" class="notinview">
                                        <div class="value">0</div>
                                        <div style="font-size:20;" class="unit"></div>
                                    </div>
                                    <div class="numerical-content">Clients</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Numerical #04 -->
                    <div class="col-xs-6 col-sm-3 animated fadeInUp delay-600">
                        <div class="center-icon" style="">
                            <i class="fa fa-coffee"></i>
                        </div>
                        <div>
                            <div class="numericals">
                                <script type="text/javascript">
                                    jQuery(window).load(function () {
                                        if (isScrolledIntoView("numerical-14")) {
                                            jQuery('#numerical-14').removeClass('notinview');
                                            incrementNumerical('#numerical-14', 840, 50);
                                        }
                                    });
                                    jQuery(window).scroll(function () {
                                        if (jQuery('#numerical-14.notinview').length) {
                                            if (isScrolledIntoView("numerical-14")) {
                                                jQuery('#numerical-14').removeClass('notinview');
                                                incrementNumerical('#numerical-14', 840, 50);
                                            }
                                        }
                                    });
                                </script>
                                <div class="numerical-container">
                                    <div id="numerical-14" class="notinview">
                                        <div class="value" style="border-right: none;">0</div>
                                        <div style="font-size:20;" class="unit"></div>
                                    </div>
                                    <div class="numerical-content">Coffees taken</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END: Row -->
            </div>
            <!-- END: NUMERICAL INCREMENT -->

            <!-- START: PARALLAX | CLIENTS LOGOS -->
            <div id="parallax-2" class="parallax"
                 style="background-image: url(https://s3.amazonaws.com/linkitesweb/parallax/parallax10.jpg);text-align:center; margin-top: 80px;">
                <div class="box-overlay-pattern">
                    <!-- Remove this line "overlay-pattern" if you don't want the overlay pattern -->
                    <div class="overlay-pattern"></div>

                    <!-- BEGIN: PARALLAX CONTENTS -->
                    <div class="parallax-content light-text">

                        <!-- BEGIN: LOGOS -->
                        <div class="recent-clients">
                            <div class="client-logos">
                                <!-- Title here -->
                                <div class="section-title">
                                    <h3>Our Awesome Clients</h3>

                                    <div class="divider-small">
                                        <div class="divider colored"></div>
                                    </div>
                                </div>

                                <!-- Your logos here -->
                                <a href="http://www.thepixelflow.com" class="animated flipInX"><img
                                        src="https://s3.amazonaws.com/linkitesweb/logos/client1.png"
                                        alt="the pixel flow"></a>
                                <a href="http://www.warnerbros.com/" class="animated flipInX delay-200"><img
                                        src="https://s3.amazonaws.com/linkitesweb/logos/client2.png" alt="Warner Bros"></a>
                                <a href="https://joust.com/" class="animated flipInX delay-400"><img
                                        src="https://s3.amazonaws.com/linkitesweb/logos/client3.png" alt="Joust"></a>
                                <a href="http://www.fieldharmony.com/" class="animated flipInX delay-600"><img
                                        src="https://s3.amazonaws.com/linkitesweb/logos/client4.png"
                                        alt="Field Harmony"></a>
                                <!--<a href="http://intlfaces.com/" class="animated flipInX delay-800"><img src="images/logos/client5.png" alt="Intlfaces"></a>-->
                            </div>
                        </div>
                        <!-- End LOGOS -->
                    </div>
                    <!-- END: PARALLAX CONTENTS -->
                </div>
            </div>
            <!-- END: PARALLAX -->
        </div>
        <!-- END: TEAM DIV -->
    </section>
    <!-- END: ABOUT SECTION -->


    <!-- BEGIN: SERVICES -->
    <section id="what_we_do" class="nav-boxes">

        <!-- BEGIN: "grey-section" WITH "section-arrow-down", "nopaddingbottom" AND "dark-text" TEXT -->
        <div class="grey-section section-arrow-down nopaddingbottom dark-text">
            <!-- Title here -->
            <div class="section-title">
                <h2><span class="bold">WHAT WE DO</span></h2>

                <div class="divider colored"></div>
                <h6 class="text-center">We bring your business goals and visions to life! Using the latest techniques in
                    mobile and web solution development.</span></h6>
            </div>

            <!-- BEGIN: SERVICES STYLE 1 CONTAINER -->
            <div class="container">
                <div>
                    <!-- SERVICE #01 -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="service">
                            <!-- Icon Column -->
                            <div class="col-xs-12 col-md-2">
                                <div class="rounded fill animated bounceIn">
                                    <!-- Icon here -->
                                    <i class="glyphicons iphone_shake"></i>
                                </div>
                            </div>

                            <!-- Description Column -->
                            <div class="col-xs-12 col-md-10">
                                <div class="text-left">
                                    <h5>RESPONSIVE DESIGN</h5>

                                    <p>Linkites is the first company in Indore deliver fully responsive site. We deliver
                                        world class designs for complex (and simple) computer systems , networks,
                                        applications and user interfaces. We uses Bootstrap3 and custom Media Query to
                                        make the site responsive.</p>
                                </div>
                            </div>

                        </div>
                    </div>

                    <!-- SERVICE #02 -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="service">
                            <div class="col-xs-12 col-md-2">
                                <div class="rounded fill animated bounceIn delay-200">
                                    <i class="glyphicons embed_close"></i>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-10">
                                <div class="text-left">
                                    <h5>CUSTOM WEB DEVELOPMENT</h5>

                                    <p>Linkites is pioneer in making your own custom-tailored web app using Node.js,
                                        Angular.js, Backbone, Meteor and PHP. We have a strong team of web developers
                                        with 8+ years of work experience who follow Trello and JIRA to update their
                                        daily activities.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- SERVICE #03 -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="service">
                            <div class="col-xs-12 col-md-2">
                                <div class="rounded fill animated bounceIn delay-400">
                                    <i class="glyphicons iphone"></i>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-10">
                                <div class="text-left">
                                    <h5>MOBILE APP DEVELOPMENT</h5>

                                    <p>We have a strong team of iOS developers and Android specialists to engineer
                                        applications on all devices, themes, and carrier combinations. iPhone/iPad App
                                        Development, Android App Development, Integration into existing infrastructure
                                        Secure, robust solutions and Collaboration with in-house designers</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <!-- SERVICE #04 -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="service">
                            <div class="col-xs-12 col-md-2">
                                <div class="rounded fill animated bounceIn delay-600">
                                    <i class="fa fa-user"></i>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-10">
                                <div class="text-left">
                                    <h5>CONSULTING SERVICES</h5>

                                    <p>Linkites architects its solutions to be self-sufficient from the root level. But
                                        if you need additional expertise, Linkites consulting services and our partner
                                        service teams are here to help.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- SERVICE #05 -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="service">
                            <div class="col-xs-12 col-md-2">
                                <div class="rounded fill animated bounceIn delay-800">
                                    <i class="fa fa-check"></i>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-10">
                                <div class="text-left">
                                    <h5>QUALITY ASSURANCE</h5>

                                    <p>We at Linkites assure client with each project to undergone the Beta and Alpha
                                        testing by performing manual and automation app testing on different devices and
                                        browsers.</p>
                                </div>
                            </div>

                        </div>
                    </div>

                    <!-- SERVICE #06 -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="service">
                            <div class="col-xs-12 col-md-2">
                                <div class="rounded fill animated bounceIn delay-1000">
                                    <i class="glyphicons cargo"></i>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-10">
                                <div class="text-left">
                                    <h5>WEB HOSTING SERVICES</h5>

                                    <p>In hosted environments, Linkites comes to you. We monitor production environments
                                        around the clock to detect issues and alerts, solving problems proactively
                                        before they reach your users. We have a vast experience in deploying app on
                                        Cloud, AWS, Linux Cent OS, Window Azure and Digital Ocean servers.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div><!-- END ROW -->
            </div><!-- END CONTAINER -->
        </div><!-- END GREY SECTION -->

        <!-- BEGIN: VIDEO SECTION -->
        <div class="master-slider ms-skin-default" id="masterslider-video">

            <!-- Overlay pattern here -->
            <div class="overlay-pattern" style="opacity:0.3;"></div>

            <!-- BEGIN: VIDEO DIV -->
            <div class="ms-slide slide-video" data-delay="15">
                <img src="masterslider/blank.gif" alt="Background image"
                     data-src="https://s3.amazonaws.com/linkitesweb/parallax/expert.jpg">
                <video data-autopause="false" data-mute="true" data-loop="true" data-fill-mode="fill">

                    <!-- Video src here -->
                    <source id="mp4" src="video/MenInBlack05.mp4" type="video/mp4"/>
                    <source id="webm" src="video/MenInBlack05.webm" type="video/webm"/>
                    <source id="ogv" src="video/MenInBlack05.ogv" type="video/ogg"/>
                </video>
            </div>

            <!-- BEGIN: VIDEO CONTENTS -->
            <div class="parallax-content light-text">
                <div class="container">
                    <!-- TITLE STYLE 1 -->
                    <div class="section-title">
                        <h2 class="text-center">We are an Expert</h2>

                        <div class="divider colored"></div>
                    </div>

                    <!-- Service #01 -->
                    <div class="col-xs-3 col-md-3 text-center animated flipInY">
                        <div class="border-box">
                            <div class="icon-nofill">
                                <i class="glyphicons embed_close"></i>
                            </div>
                            <h5>WEB DEVELOPMENT</h5>

                            <p>Come and experience the cool web apps using Node.js and other JavaScript Frameworks</p>
                        </div>
                    </div>

                    <!-- Service #02 -->
                    <div class="col-xs-3 col-md-3 text-center animated flipInY delay-200">
                        <div class="border-box">
                            <div class="icon-nofill">
                                <i class="glyphicons iphone"></i>
                            </div>
                            <h5>MOBILE APPLICATION</h5>

                            <p>No matter Native or Cross Platform we have a solution for both</p>
                        </div>
                    </div>

                    <!-- Service #03 -->
                    <div class="col-xs-3 col-md-3 text-center animated flipInY delay-400">
                        <div class="border-box">
                            <div class="icon-nofill">
                                <i class="glyphicons sort"></i>
                            </div>
                            <h5>DATABASE</h5>

                            <p>Thinking about noSql we have a wide solution for you like MongoDB, OrientDB, GraphDB and
                                CouchDB.</p>
                        </div>
                    </div>

                    <!-- Service #04 -->
                    <div class="col-xs-3 col-md-3 text-center animated flipInY delay-600">
                        <div class="border-box">
                            <div class="icon-nofill">
                                <i class="glyphicons cargo"></i>
                            </div>
                            <h5>SERVER HOSTING</h5>

                            <p>Our Infra team will provide you best solution for hosting your app</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END: VIDEO CONTENTS -->
        </div>
        <!-- END: VIDEO SECTION -->
    </section>
    <!-- END: SERVICES SECTION -->


    <!-- BEGIN: PORTFOLIO SECTION -->
    <section id="portfolio" class="grey-section dark-text nopaddingbottom nav-boxes">

        <!-- BEGIN: PROJECTS TITLE -->
        <div class="container">
            <div class="section-title">
                <h2>The <span class="bold">Work</span> We Do</h2>

                <div class="divider colored"></div>
                <h3 class="title-desc-big">We have done some of the awesome projects both in Web and Mobile
                    Technology.</h3>
            </div>
        </div>

        <!-- BEGIN: AJAX LOADING -->
        <div class="container">
            <div>
                <div id="loader"></div>
            </div>
        </div>

        <!-- BEGIN: PROJECTS -->
        <div>
            <div id="main">
                <div class="main_inner wrapper clearfix">
                    <div class="container">
                        <!-- BEGIN: CATEGORY FILTER -->
                        <ul id="projects-filter" class="filter" data-option-selected="*">
                            <li><a class="active" data-option-value="*" href="javascript:;">All</a></li>
                            <li><a data-option-value=".web" href="javascript:;">WEB</a></li>
                            <li><a data-option-value=".iphone" href="javascript:;">iPhone</a></li>
                            <li><a data-option-value=".android" href="javascript:;">Android</a></li>
                            <li><a data-option-value=".node" href="javascript:;">Node.js</a></li>
                            <li><a data-option-value=".Titanium" href="javascript:;">Titanium</a></li>
                        </ul>
                        <!-- END: CATEGORY FILTER -->
                    </div>

                    <!-- BEGIN: PROJECTS THUMBNAILS -->
                    <div class="entries clearfix" id="works_masonry">
                        <ul class="grid cs-style-3">

                            <!-- PROJECT #01 | LINK + TOOLTIP -->
                            <li class="masonry_item one-third column work web node">
                                <figure>
                                    <img alt="Field Harmony"
                                         src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb1.jpg">

                                    <div class="figcaption">
                                        <h3>Field Harmony</h3>
                                        <span class="p-tags">Web</span>

                                        <!--<a class="loadcontent thumb-link trigger-overlay" href="proj-bigimages.html" data-title="ProjectBigImages" data-toggle="tooltip" data-placement="top" title="View Project"><i class="glyphicons link"></i></a>-->
                                    </div>
                                </figure>
                            </li>

                            <!-- PROJECT #02 | CENTER TEXT -->
                            <li class="masonry_item one-third column work iphone node">
                                <figure>
                                    <!--<a class="loadcontent trigger-overlay" href="proj-slider.html" data-title="ProjectWideSlider">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb2.jpg" alt="StylePic">

                                    <div class="figcaption">
                                        <h3>StylePic</h3>
                                        <span>iOS App</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #03 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web node">
                                <figure>
                                    <!--<a class="loadcontent trigger-overlay" href="proj-bigimages2.html" data-title="ProjectWideSlider2">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb3.jpg" alt="Tradie">

                                    <div class="figcaption">
                                        <h3>Tradie</h3>
                                        <span>Web</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #04 | LINK + TOOLTIP -->
                            <li class="masonry_item one-third column work web iphone android">
                                <figure>
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb4.jpg" alt="mSchools">

                                    <div class="figcaption">
                                        <h3>mSchools</h3>
                                        <span>Responsive Web App | iOS App | Android App</span>

                                        <!--<a class="loadcontent thumb-link trigger-overlay" href="proj-slider-v.html" data-title="Project12Slider" data-toggle="tooltip" data-placement="top" title="View Project"><i class="glyphicons link"></i></a>-->
                                    </div>
                                </figure>
                            </li>

                            <!-- PROJECT #05 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web">
                                <figure>
                                    <!--<a class="loadcontent trigger-overlay text-center" href="proj-bigimages3.html" data-title="ProjectWideSlider3">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb5.jpg"
                                         alt="Warner Bros.">

                                    <div class="figcaption">
                                        <h3>Best of Warner Bros.</h3>
                                        <span>Web</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #06 | LINK + TOOLTIP ->
                            <li class="masonry_item one-third column work web node">
                                <figure>
                                    <img src="images/portfolio/thumb6.jpg" alt="Ship Overseas">
                                    <div class="figcaption">
                                        <h3>Ship Overseas</h3>
                                        <span>Web</span>

                                        <!--<a class="loadcontent thumb-link trigger-overlay" href="proj-bigimages.html" data-title="ProjectWideSlider" data-toggle="tooltip" data-placement="top" title="View Project"><i class="glyphicons link"></i></a>->
                                    </div>
                                </figure>
                            </li>

                            <!-- PROJECT #07 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web node">
                                <figure>
                                    <!--<a class="loadcontent trigger-overlay" href="proj-slider4.html" data-title="ProjectWideSlider">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb7.jpg"
                                         alt="Search Wizer">

                                    <div class="figcaption">
                                        <h3>Search Wizer</h3>
                                        <span>Responsive Web</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #08 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web node">
                                <figure>
                                    <!--<a class="loadcontent trigger-overlay" href="proj-bigimages4.html" data-title="ProjectWideSlider4">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb8.jpg" alt="Joust">

                                    <div class="figcaption">
                                        <h3>Joust</h3>
                                        <span>Responsive Web</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #09 | CENTER TEXT | VIDEO ->
                            <li class="masonry_item one-third column work iphone">
                                <figure>
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb9.jpg" alt="Memoji">
                                    <div class="figcaption">
                                        <h3>Memoji</h3>
                                        <span>iOS App</span>

                                        <!--<a class="loadcontent thumb-link trigger-overlay" href="proj-video.html" data-title="ProjectVideo" data-toggle="tooltip" data-placement="top" title="View Video"><i class="glyphicons link"></i></a>->
                                    </div>
                                </figure>
                            </li>

                            <!-- PROJECT #10 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web iphone android">
                                <figure>
                                    <!--<a class="text-center loadcontent trigger-overlay" href="proj-slider-v2.html" data-title="Reflexion">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb10.jpg"
                                         alt="Schoolry">

                                    <div class="figcaption">
                                        <h3>Schoolry</h3>
                                        <span>Responsive Web | iOS App | Android App</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #11 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web iphone android">
                                <figure>
                                    <!--<a class="text-center loadcontent trigger-overlay" href="proj-slider3.html" data-title="cup">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb11.jpg"
                                         alt="Indus International School">

                                    <div class="figcaption">
                                        <h3>Indus International School</h3>
                                        <span>Responsive Web App | iOS App | Android App</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>

                            <!-- PROJECT #12 | CENTER TEXT -->
                            <li class="masonry_item one-third column work web iphone android">
                                <figure>
                                    <!--<a class="loadcontent trigger-overlay" href="proj-slider.html" data-title="ProjectWideSlider">-->
                                    <img src="https://s3.amazonaws.com/linkitesweb/portfolio/thumb12.jpg"
                                         alt="Pocket Scheduler">

                                    <div class="figcaption">
                                        <h3>Pocket Scheduler</h3>
                                        <span>Responsive Web App | iOS App | Android App</span>
                                    </div>
                                    <!--</a>-->
                                </figure>
                            </li>
                        </ul>
                    </div>
                    <!-- END: PROJECTS THUMBNAILS -->
                </div>
            </div>
        </div>
        <!-- END: PROJECTS -->

        <!-- BEGIN: CLIENTS SECTION -->
        <div class="light-section">

            <!-- TILE HERE -->
            <div class="section-title">
                <h2><span class="bold">Clients</span> Feedback</h2>

                <div class="divider colored"></div>
            </div>

            <!-- BEGIN: TESTIMONIALS SLIDER -->
            <div id="testimonials-slider" class="flexslider">
                <ul class="slides styled-list">

                    <!-- SLIDE #01 -->
                    <li class="testimonials-slide">
                        <div class="testimonials-slide-content container">
                            <!-- CLIENT IMAGE HERE -->
                            <div class="img-container">
                                <img title="" src="https://s3.amazonaws.com/linkitesweb/team/8.jpg" alt="Warren Bailey">
                            </div>

                            <!-- CLIENT TESTIMONIAL HERE -->
                            <div class="text-container">
                                <!-- AUTHOR -->
                                <span class="t-author">Warren Bailey, MD @ Satellite Intelligence Group</span>

                                <p><i class="fa fa-quote-left"></i> Top notch service. Absolutely recommend. We looked
                                    for hours and poured over lame proposals until we took a chance (our first on this
                                    site) and they've hit a home run for us so far. Honesty, hard working, diligent.
                                    They are able to understand us without us having to clarify or talk to them like
                                    they are in a third world country. Fantastic work, we really appreciate it. <i
                                        class="fa fa-quote-right"></i></p>
                            </div>
                        </div>
                    </li>

                    <!-- SLIDE #02 -->
                    <li class="testimonials-slide">
                        <div class="testimonials-slide-content container">
                            <div class="img-container">
                                <img title="" src="https://s3.amazonaws.com/linkitesweb/team/7.jpg" alt="Dennis Dupont">
                            </div>

                            <div class="text-container">
                                <span class="t-author">Dennis Dupont, CTO @ intelemedia</span>

                                <p><i class="fa fa-quote-left"></i> Excellent group to work with. Will continue to use
                                    them on future projects. Very responsive and collaborative. Excellent software craft
                                    with online git hub and jira issue tracking. <i class="fa fa-quote-right"></i></p>
                            </div>
                        </div>
                    </li>

                    <!-- SLIDE #03 -->
                    <li class="testimonials-slide">
                        <div class="testimonials-slide-content container">
                            <div class="img-container">
                                <img title="" src="https://s3.amazonaws.com/linkitesweb/team/6.jpg" alt="Charles Hu">
                            </div>

                            <div class="text-container">
                                <span class="t-author">Charles Hu, CEO @ Fishermenlabs</span>

                                <p><i class="fa fa-quote-left"></i> Love working with them, quick, professional, and
                                    high quality. <i class="fa fa-quote-right"></i></p>
                            </div>
                        </div>
                    </li>

                    <!-- SLIDE #04 -->
                    <li class="testimonials-slide">
                        <div class="testimonials-slide-content container">
                            <div class="img-container">
                                <img title="" src="https://s3.amazonaws.com/linkitesweb/team/9.jpg" alt="Mario Venture">
                            </div>

                            <div class="text-container">
                                <span class="t-author">Mario Venture, CEO @ Myffers Inc.</span>

                                <p><i class="fa fa-quote-left"></i> Easy to deal with very flexible and accommodating
                                    with A+++ service. <i class="fa fa-quote-right"></i></p>
                            </div>
                        </div>
                    </li>

                    <!-- SLIDE #05 -->
                    <li class="testimonials-slide">
                        <div class="testimonials-slide-content container">
                            <div class="img-container">
                                <img title="" src="https://s3.amazonaws.com/linkitesweb/team/10.jpg" alt="Chris Dobler">
                            </div>

                            <div class="text-container">
                                <span class="t-author">Chris Dobler, Sr. Programmer	@ VDIC</span>

                                <p><i class="fa fa-quote-left"></i> They are very attentive to issues, would recommend
                                    them highly. <i class="fa fa-quote-right"></i></p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div><!-- END FLEXSLIDER -->
            <div class="space"></div>
            <div class="space"></div>
        </div> <!-- end of light section -->

        <!-- START: PARALLAX - PROCESS ICONS ->
        <div id="parallax-3" class="parallax" style="background-image: url(https://s3.amazonaws.com/linkitesweb/parallax/9.jpg);text-align:center;">
            <div class="box-overlay-pattern">
              <!-- Remove this line "overlay-pattern" if you don't want the overlay pattern ->
              <div class="overlay-pattern soft"></div>
              <div class="parallax-content mediumpadding light-text">
                  <div class="icon-author animated flipInX">
                      <div class="bird"></div>
                      <p class="twitter-author"><a href="http://twitter.com/'envato'" target="_blank">Follow us on Twitter</a></p>
                  </div>

                  <!-- Twitter Slider ->
                  <div class="twitter-slider">
                      <div id="twitter-feed"></div>
                  </div>
              </div>
            </div>
            <!-- END box-overlay-pattern ->
        </div>
        <!-- END: PARALLAX -->

    </section>
    <!-- END: PORTFOLIO SECTION -->

    <!-- BEGIN: #CONTACT SECTION -->
    <section id="contacts" class="nav-boxes">
        <!-- START: PARALLAX CONTACTS -->
        <div id="parallax-contacts" class="parallax"
             style="background-image: url(https://s3.amazonaws.com/linkitesweb/parallax/6.jpg);text-align:center;">
            <div class="box-overlay-pattern">
                <div class="overlay-pattern soft dark"></div>

                <!-- BEGIN: PARALLAX CONTENT -->
                <div class="parallax-content smallpadding">

                    <!-- TITLE -->
                    <div class="section-title light">
                        <h2>CONTACT US</h2>

                        <div class="divider colored"></div>
                    </div>

                    <!-- BEGIN: CONTACTS FORM -->
                    <div class="container bg-mobiles">
                        <div class="col-xs-12 col-md-8">
                            <div class="bgpattern">
                                <!-- CONTACT FORM -->
                                <div id="contact_form">
                                    <div class="location">
                                        <h3><span class="text_color">Drop us a line</span></h3>
                                    </div>

                                    <!-- Sucess Message -->
                                    <div class="form-success">
                                        <p><i class="fa fa-check"></i>Thank you, your message has been sent.</p>
                                    </div>

                                    <!-- Begin form -->
                                    <div class="contact-form">
                                        <form action="contact-form/send.php" method="post" class="form">
                                            <div class="name">
                                                <input class="text" type="text" name="name" placeholder="Name">
                                            </div>
                                            <div class="email">
                                                <input class="text" type="text" name="email" placeholder="E-mail">
                                            </div>
                                            <div class="subject">
                                                <input class="text" type="text" name="subject" placeholder="Subject">
                                            </div>

                                            <div class="service">
                                                <select name="services" required>
                                                    <i class="fa fa-chevron-down cerat-arw"></i>

                                                    <option value="">Type of Service</option>
                                                    <option value="web">iOS 8 Development</option>
                                                    <option value="web">Web Design</option>
                                                    <option value="branding">Branding</option>
                                                    <option value="illustration">Illustration &amp; Print</option>
                                                    <option value="illustration">Mobile App Development</option>
                                                    <option value="Web Development"><!--Web Design &amp;-->Web
                                                        Development
                                                    </option>
                                                    <option value="SEO">SEO &amp; SMM</option>
                                                    <option value="Other">Other</option>
                                                </select>
                                            </div>

                                            <input class="service-input" type="text" name="service"
                                                   style="display:none;">

                                            <div class="message eight columns">
                                                <textarea name="message" rows="8" cols="60" placeholder="Message"
                                                          required></textarea></div>
                                            <div class="subject-new">

                                                <input name="verif_box" type="text" id="verif_box"
                                                       placeholder="Type verification image text"/>
                                                <img src="http://www.linkites.com/verificationimage.php"
                                                     alt="verification image, type it in the box" width="50"
                                                     height="24"/>
                                            </div>

                                            <div class="sendd">
                                                <a class="p-button border lightSpeedIn" id="submit" href="javascript:;"><i
                                                        class="fa fa-check-circle-o"></i><span class="with-icon">SEND EMAIL</span></a>

                                                <div class="loading"></div>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- End form -->
                                </div>
                                <!-- END CONTACT FORM -->
                            </div>
                        </div>

                        <!-- Begin Bg Mobiles -->
                        <div>
                            <!-- Other Contacts -->
                            <div class="col-xs-12 col-md-4">
                                <div class="bgpattern">
                                    <div class="othercontacts">
                                        <h3><span class="text_color">Contact Details</span></h3>
                                        <ul class="contacts">
                                            <li><i class="fa fa-map-marker"></i>6th Floor, Crystal IT Park,
                                            </li>
                                            <li>Building No. 1, Right Hand Side , SEZ</li>
                                            <li>Indore (MP), India</li>
                                            <li><i class="fa fa-envelope" style="left: -3px;"></i><a
                                                    href="mailto:info@linkites.com">info@linkites.com</a></li>
                                            <li><i class="fa fa-phone"></i>+91 731 297 0465</li>
                                            <!--<li><i class="fa fa-print"></i>+351 422 311 432</li>-->
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <br/>

                            <!-- Social -->
                            <div class="col-xs-12 col-md-4">
                                <div class="bgpattern">
                                    <div class="othercontacts social">
                                        <h3><span class="text_color">We are Social</span></h3>

                                        <div class="dark">
                                            <a href="https://www.facebook.com/pages/Linkites-Infotech-Pvt-Ltd/1401429756848399?ref=aymt_homepage_panel"
                                               class="social facebook animated fadeInUp" title="Facebook"></a>
                                            <a href="skype:Linkites?add"
                                               class="social skype animated fadeInUp delay-800" title="Skype"></a>
                                            <a href="mailto:info@linkites.com"
                                               class="social e-mail animated fadeInUp delay-1000" title="E-Mail"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End Social -->
                        </div>
                        <!-- End bg Mobiles -->
                    </div> <!-- end of .container -->
                </div><!-- end: .parallax-contant -->
            </div><!-- end .box-overlay-pattern -->
        </div>
        <!-- END: PARALLAX #03 -->

    </section>
    <!-- END: #CONTACTS SECTION -->


    <!-- BEGIN BOTTOM FOOTER -->
    <section id="bottom-footer">
        <div class="container text-center">
            <p>&copy; Copyright 2015, all rights reserved.</p>
            <!--<p>View <a href="home-icons.html">Home Icons Demo</a> or <a href="home-fs-video.html">Home Parallax Demo</a>-->
        </div>
    </section>
    <!-- END BOTTOM FOOTER -->
</div>
<!-- END .everything -->

<div class="quick-contact noView">
    <div class="quick-form">
        <div class="show-me"><span class="fa fa-angle-double-left fa-2x"></span></div>
        <h1>Submit Your Requirement</h1>

        <form method="post" name="mainform" action="sendrequirement.php" onSubmit="return validate()">
            <input type="text" name="name" placeholder="Full Name" required>
            <input type="email" name="email" placeholder="Email Address" required>
            <input type="text" name="contact" placeholder="Contact Number" required>
            <textarea name="description" required></textarea>

            <button type="submit" name="submit">Submit</button>
        </form>
    </div>
</div>

<!-- GO TOP BUTTON -->
<p id="back-top"><a href="#home"></a></p>

<!-- BEGIN: PROJECT LOADER -->
<!-- ALL THE PROJECT DETAILS WILL BE LOADED IN THIS AREA -->
<div class="projects-overlay overlay-contentpush">
    <div id="projects-loader"></div>
    <div class="projects-overlay-content">
        <div id="pagecontent" class="container">
            <div class="pageXofY">
                <span class="pageX"></span> / <span class="ofY"></span>
            </div>
            <div class="scrollbar">
                <div class="track">
                    <div class="thumb">
                        <div class="end"></div>
                    </div>
                </div>
            </div>
            <div class="viewport">
                <div class="overview">
                    <div id="pageloader" class="container">
                        <!-- THE LOADED CONTENT WILL SHOW HERE -->
                    </div>
                </div>
            </div>
        </div>
        <button type="button" class="overlay-close">Close</button>
        <nav class="projects-navigation">
            <div class="prev-proj">
                <a href="javascript:;">prev</a>
            </div>
            <div class="next-proj">
                <a href="javascript:;">next</a>
            </div>
        </nav>
    </div>
</div>
<!-- END -->

<!-- LOAD OTHER SCRIPTS -->
<script src="assets/js/paris.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/typed.js" type="text/javascript"></script>
<script>
    var k = 0;
    var techs = [];
    var pAndC;
    var nodejsStrings = [];
    var angularjsStrings = [];
    var meteorjsStrings = [];
    var knockoutjsStrings = [];
    var ionicStrings = [];
    var androidStrings = [];
    var iosString = [];
    var newStrings = [];
    var Titanium = [];
    var index = -1;
    var counter = 0;
    var proj_counter = 0;

    Constants = {
        Client_counter_Speed: 150,
        Project_counter_Speed: 150,    // Speed of counter on left and right side
        Typing_Speed: 50,
        Number_of_Slides: 6         // Total number of slides  in slider
    }


    $.ajax({
        dataType: "json",
        url: "datajson.php",
        data: k,
        success: function (params) {
            techs = params.technologies;
            pAndC = params.projectAndClient;
            nodejsStrings = params.nodejsStrings;
            angularjsStrings = params.angularjsStrings;
            meteorjsStrings = params.meteorjsStrings;
            knockoutjsStrings = params.knockoutjsStrings;
            ionicStrings = params.ionicStrings;
            androidStrings = params.androidStrings;
            iosString = params.iosString;
            Titanium = params.Titanium;
            newStrings = params.newStrings;
            index = -1;
            newTyped();
        }
    });


    function newTyped() {
        index++;
        if (index > Constants.Number_of_Slides) {
            index = 0;
        }

        var tech = techs[index];
        switch (tech) {
            case 'NodeJS':
                newStrings = nodejsStrings;
                break;
            case 'AngularJS':
                newStrings = angularjsStrings;
                break;
            case 'MeteorJS':
                newStrings = meteorjsStrings;
                break;
            case 'KnockouJS':
                newStrings = knockoutjsStrings;
                break;
            case 'Ionic':
                newStrings = ionicStrings;
                break;
            case 'Android':
                newStrings = androidStrings;
                break;
            case 'Ios':
                newStrings = iosString;
                break;
            case 'Titanium' :
                newStrings = Titanium;
                break;
        }
        $(".logo-wrap").find("." + tech).fadeIn(10);

        function proje_counter() {

            setTimeout(function projcounter() {
                if (proj_counter <= pAndC[tech].projects) {
                    var str = '';
                    if (proj_counter < 10) {
                        str += '0';
                    } else {
                        str += '';
                    }
                    $(".Project-figure").text(str + proj_counter).fadeIn(10);
                    proj_counter++;
                    proje_counter();
                }
                else {
                    proj_counter = 0;
                    return false;
                }

            }, Constants.Client_counter_Speed);
        }

        // $(".client-figure").text(pAndC[tech].clients);
        function client_counter() {

            setTimeout(function clientcounter() {
                if (counter <= pAndC[tech].clients) {
                    var str = '';
                    if (counter < 10) {
                        str += '0';
                    } else {
                        str += '';
                    }
                    $(".client-figure").text(str + counter).fadeIn(500);
                    ;
                    counter++;
                    client_counter();
                }
                else {
                    counter = 0;
                    return false;
                }

            }, Constants.Project_counter_Speed);
        }

        client_counter();
        proje_counter();

        //   console.log( "pac" , pAndC[tech].clients );
        //  $(".Project-figure").text(pAndC[tech].projects).fadeIn(500);
        $("#" + tech).fadeIn(500);
        $("#tags").text(pAndC[tech].Taglines);

        $("#typed").typed({
            strings: newStrings,
            typeSpeed: Constants.Typing_Speed,   // 50
            backDelay: 500,   // 500
            loop: false,
            contentType: 'html', // or text
            // defaults to false for infinite loop
            loopCount: false,
            callback: function () {
                nextTech();
            },
            resetCallback: function () {
                $(".logo-wrap").find(".img-responsive").fadeOut(500);
                $("#" + tech).fadeOut(500);
                $("#typed").fadeOut(500);
                $(".logo-list").fadeOut(500);
                //$(".client-figure").fadeOut(500);
                //$(".Project-figure").fadeOut(500);
                setTimeout(function () {
                    newTyped();
                }, 1000);
            }
        }).fadeIn(1000);
    }

    function nextTech() {
        setTimeout(function () {
            $("#typed").typed('reset');
        }, 500);
    }


</script>
<script>
    //$('.quick-form').css('display', 'none');
    $(document).ready(function () {
        $('#fetr-wrk1').addClass('importantRule');

        $('.show-me').click(function () {
            if ($('.quick-contact').hasClass('noView')) {
                $('.quick-contact').animate({'right': 0}, 300).removeClass('noView');
                $('.show-me > .fa').addClass('turn-me');
                $('.show-me').addClass('change-me');
            } else {
                $('.quick-contact').animate({'right': '-300px'}, 300).addClass('noView');
                $('.show-me > .fa').removeClass('turn-me');
                $('.show-me').removeClass('change-me');
            }
            ;
        });
    });
</script>
<script>
    function validate() {

        var name = document.mainform.name.value;
        if (!isNaN(name)) {
            alert("Please Enter Only Characters");
            document.mainform.name.focus();
            return false;
        }

        var emailID = document.mainform.email.value;

        atpos = emailID.indexOf("@");
        dotpos = emailID.lastIndexOf(".");
        if (atpos < 1 || ( dotpos - atpos < 2 )) {
            alert("Please enter correct email ID")
            document.mainform.email.focus();
            return false;
        }

        var val = document.mainform.contact.value;
        if (/^\d{10}$/.test(val)) {
            // value is ok, use it
        } else {
            alert("Invalid number; must be ten digits")
            document.mainform.contact.focus();
            return false;
        }
    }
</script>

</body>
</html>