
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0">
    <meta name="p:domain_verify" content="dd668c2ae785fae2ea70e66ef33edba7"/>
    <meta name="alexaVerifyID" content="Dmkd6Dz3tVeuJSrnGL0z1Tow6ZY"/>
    <meta name="keywords"
          content="Software Development Company, software development, IT Outsourcing Services, Offshore Software Development, Offshore Outsourcing Services, Outsourced Product Development, Mobile Application Development, Web Design and development, Search Engine Optimization, SEO Services, web design company, web design, node js mobile application, node js development company, mongo nosql">
    <meta name="description"
          content="LinkITes - Software Development Company | IT Outsourcing Services | Outsourced Product Development | Mobile Application Development |  Web Design and Development | Search Engine Optimization | node js development company">
    <meta name="author" content="Linkites">
    <meta name='yandex-verification' content='754464d9b64e5e3b'/>

    <link rel="shortcut icon" href="https://s3.amazonaws.com/linkitesweb/favicon.png">
    <title>LinkITes - Software Development Company | IT Outsourcing Services | Outsourced Product Development | Mobile
        Application Development | Web Design and Development | node js development company</title>

    <!-- LOAD CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/interface.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/css/icons-font.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/masterslider/style/masterslider.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/masterslider/skins/default/style.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/masterslider/skins/designare/style.css" rel='stylesheet' type='text/css' media="screen">
    <link href="assets/css/layout.css" rel="stylesheet" type="text/css" media="screen">

    <!-- SLIDER REVOLUTION 4.x DESIGNARE CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="assets/rs-plugin/css/designare-settings.css" media="screen"/>

    <!-- COLORS -->
    <link href="assets/css/color-variations/decor.css" rel="stylesheet" type="text/css" media="screen" title="linkites">

    <!-- USED FOR RESPONSIVE ADJUSTMENTS -->
    <link href="assets/css/resize.css" rel="stylesheet" type="text/css" media="screen">
    <link href="assets/css/style.css" rel="stylesheet" type="text/css" media="screen">
    <!-- LOAD GOOGLE FONTS -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:100,300,600,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:600,800' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Load JQuery at this point if you use the Numerical Increments in your page -->
    <script src="assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="assets/js/utils.js" type="text/javascript"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="assets/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="assets/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-38277461-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!--Verification: 754464d9b64e5e3b-->

    <!--popup js -->
    <script src="assets/js/bootstrap.js"></script>
    <!--  <script type="text/javascript">

     $(document).ready(function(){
         $("#myModal").modal('show');
     });
 </script>-->

    <!--end of popup css-->
</head>
<body>
<!--
<div id="myModal" class="modal fade landing_model">
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-content_bg">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title">Meet Us at Gitex - Dubai 18th-22nd Oct</h4>
        </div>
        <div class="modal-body">
            <div class="gitex_img"><img src="https://s3.amazonaws.com/linkitesweb/gitex_poup_logo.png" class="img-responsive"> </div>
            <p class="stand_text">Sheikh Rashid Hall Stand:SR-E10</p>

            <h5>Dubai World Trade Centre</h5>

        </div>
        <div class="modal-footer">

          <a href= "http://www.gitex.com/page.cfm/Action=Exhib/ExhibID=850/loadSearch=372723_7944" target="_blank" class=" btn btn-primary">View More</a>
        </div>
    </div>
    </div>
</div>
</div>
-->


<div id="load"></div>
<div class="everything">
    <!-- BEGIN: HEADER BAR
         OPTIONS: "dark", "style2", "style1", "border" and "hide-on-start"
    -->
    <div class="navbar navbar-default style2 navbar-fixed-top" role="navigation">
        <!-- BEGIN: NAV-CONTAINER -->
        <div class="nav-container">
            <div class="navbar-header">
                <!-- BEGIN: TOGGLE BUTTON (RESPONSIVE)-->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- BEGIN: LOGO -->
                <a class="navbar-brand nav-to" href="index.php">
                    <img class="img-responsive link-logo" src="https://s3.amazonaws.com/linkitesweb/Linkites-logos.png"
                         alt="Linkites: IT Services, Consulting and Business Solutions">
                </a>
            </div>

            <!-- BEGIN: MENU -->

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!--
                 <li class="portfolio_text">
                        MEET US AT
                    </li>
                    <li>
                      <a class="portfolio-page" href="http://www.gitex.com/page.cfm/Action=Exhib/ExhibID=850/loadSearch=372723_7944" target="_blank">
                        <img src="https://s3.amazonaws.com/linkitesweb/gitex_logo.png" alt="Portfolio Page">
                      </a>
                    </li>-->
                    <li><a href="#home">HOME</a></li>
                    <li><a href="#who_we_are">Who we are</a>
                        <ul class="dropdown-menu">
                            <li><a href="#about">About Us</a></li>
                            <li><a href="#featured">Featured Works</a></li>
                            <li><a href="#team">Meet the Team</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-to" href="index.php#what_we_do">What we do</a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-to" href="androiddevelopment.html">Android Development</a></li>
                            <li><a class="nav-to" href="iOSdevelopment.html">iOS Development</a></li>
                            <li><a class="nav-to" href="meteordevelopment.html">Meteor Development</a></li>
                            <li><a class="nav-to" href="nodejsdevelopment.html">Nodejs Development</a></li>
                        </ul>
                    </li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="career.html">Career</a></li>
                    <li><a href="#contacts">Contact</a></li>
                </ul>
            </div>


            <!-- END: MENU -->
        </div>
        <!--END: NAV-CONTAINER -->
    </div>
    <!-- END: HEADER BAR -->

    <section id="moving-text">
        <marquee>

            <span>Latest News:</span>

		<span><i class="fa fa-angle-double-left str-clr"></i>
		Linkites has now started developing iPhone app using latest  IOS Swift to know more, <a
                href="https://developer.apple.com/swift/">click here</a>.</span>

            <!--<span><i class="fa fa-angle-double-left str-clr"></i>
            Job Hirings:Click here for <a href="http://www.linkites.com/career.html">
            Apply Now</a> and check the <a href="http://www.linkites.com/career.html">Interview status</a>.--></span>


        </marquee>
    </section>


    <?php
            // Load view content
            echo $this->getContent();exit;
     ?>

    <!-- BEGIN: #CONTACT SECTION -->
    <section id="contacts" class="nav-boxes">
        <!-- START: PARALLAX CONTACTS -->
        <div id="parallax-contacts" class="parallax"
             style="background-image: url(https://s3.amazonaws.com/linkitesweb/parallax/6.jpg);text-align:center;">
            <div class="box-overlay-pattern">
                <div class="overlay-pattern soft dark"></div>

                <!-- BEGIN: PARALLAX CONTENT -->
                <div class="parallax-content smallpadding">

                    <!-- TITLE -->
                    <div class="section-title light">
                        <h2>CONTACT US</h2>

                        <div class="divider colored"></div>
                    </div>

                    <!-- BEGIN: CONTACTS FORM -->
                    <div class="container bg-mobiles">
                        <div class="col-xs-12 col-md-8">
                            <div class="bgpattern">
                                <!-- CONTACT FORM -->
                                <div id="contact_form">
                                    <div class="location">
                                        <h3><span class="text_color">Drop us a line</span></h3>
                                    </div>

                                    <!-- Sucess Message -->
                                    <div class="form-success">
                                        <p><i class="fa fa-check"></i>Thank you, your message has been sent.</p>
                                    </div>

                                    <!-- Begin form -->
                                    <div class="contact-form">
                                        <form action="contact-form/send.php" method="post" class="form">
                                            <div class="name">
                                                <input class="text" type="text" name="name" placeholder="Name">
                                            </div>
                                            <div class="email">
                                                <input class="text" type="text" name="email" placeholder="E-mail">
                                            </div>
                                            <div class="subject">
                                                <input class="text" type="text" name="subject" placeholder="Subject">
                                            </div>

                                            <div class="service">
                                                <select name="services" required>
                                                    <i class="fa fa-chevron-down cerat-arw"></i>

                                                    <option value="">Type of Service</option>
                                                    <option value="web">iOS 8 Development</option>
                                                    <option value="web">Web Design</option>
                                                    <option value="branding">Branding</option>
                                                    <option value="illustration">Illustration &amp; Print</option>
                                                    <option value="illustration">Mobile App Development</option>
                                                    <option value="Web Development"><!--Web Design &amp;-->Web
                                                        Development
                                                    </option>
                                                    <option value="SEO">SEO &amp; SMM</option>
                                                    <option value="Other">Other</option>
                                                </select>
                                            </div>

                                            <input class="service-input" type="text" name="service"
                                                   style="display:none;">

                                            <div class="message eight columns">
                                                <textarea name="message" rows="8" cols="60" placeholder="Message"
                                                          required></textarea></div>
                                            <div class="subject-new">

                                                <input name="verif_box" type="text" id="verif_box"
                                                       placeholder="Type verification image text"/>
                                                <img src="http://www.linkites.com/verificationimage.php"
                                                     alt="verification image, type it in the box" width="50"
                                                     height="24"/>
                                            </div>

                                            <div class="sendd">
                                                <a class="p-button border lightSpeedIn" id="submit" href="javascript:;"><i
                                                        class="fa fa-check-circle-o"></i><span class="with-icon">SEND EMAIL</span></a>

                                                <div class="loading"></div>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- End form -->
                                </div>
                                <!-- END CONTACT FORM -->
                            </div>
                        </div>

                        <!-- Begin Bg Mobiles -->
                        <div>
                            <!-- Other Contacts -->
                            <div class="col-xs-12 col-md-4">
                                <div class="bgpattern">
                                    <div class="othercontacts">
                                        <h3><span class="text_color">Contact Details</span></h3>
                                        <ul class="contacts">
                                            <li><i class="fa fa-map-marker"></i>6th Floor, Crystal IT Park,
                                            </li>
                                            <li>Building No. 1, Right Hand Side , SEZ</li>
                                            <li>Indore (MP), India</li>
                                            <li><i class="fa fa-envelope" style="left: -3px;"></i><a
                                                    href="mailto:info@linkites.com">info@linkites.com</a></li>
                                            <li><i class="fa fa-phone"></i>+91 731 297 0465</li>
                                            <!--<li><i class="fa fa-print"></i>+351 422 311 432</li>-->
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <br/>

                            <!-- Social -->
                            <div class="col-xs-12 col-md-4">
                                <div class="bgpattern">
                                    <div class="othercontacts social">
                                        <h3><span class="text_color">We are Social</span></h3>

                                        <div class="dark">
                                            <a href="https://www.facebook.com/pages/Linkites-Infotech-Pvt-Ltd/1401429756848399?ref=aymt_homepage_panel"
                                               class="social facebook animated fadeInUp" title="Facebook"></a>
                                            <a href="skype:Linkites?add"
                                               class="social skype animated fadeInUp delay-800" title="Skype"></a>
                                            <a href="mailto:info@linkites.com"
                                               class="social e-mail animated fadeInUp delay-1000" title="E-Mail"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End Social -->
                        </div>
                        <!-- End bg Mobiles -->
                    </div> <!-- end of .container -->
                </div><!-- end: .parallax-contant -->
            </div><!-- end .box-overlay-pattern -->
        </div>
        <!-- END: PARALLAX #03 -->

    </section>
    <!-- END: #CONTACTS SECTION -->


    <!-- BEGIN BOTTOM FOOTER -->
    <section id="bottom-footer">
        <div class="container text-center">
            <p>&copy; Copyright 2015, all rights reserved.</p>
            <!--<p>View <a href="home-icons.html">Home Icons Demo</a> or <a href="home-fs-video.html">Home Parallax Demo</a>-->
        </div>
    </section>
    <!-- END BOTTOM FOOTER -->
</div>
<!-- END .everything -->

<div class="quick-contact noView">
    <div class="quick-form">
        <div class="show-me"><span class="fa fa-angle-double-left fa-2x"></span></div>
        <h1>Submit Your Requirement</h1>

        <form method="post" name="mainform" action="sendrequirement.php" onSubmit="return validate()">
            <input type="text" name="name" placeholder="Full Name" required>
            <input type="email" name="email" placeholder="Email Address" required>
            <input type="text" name="contact" placeholder="Contact Number" required>
            <textarea name="description" required></textarea>

            <button type="submit" name="submit">Submit</button>
        </form>
    </div>
</div>

<!-- GO TOP BUTTON -->
<p id="back-top"><a href="#home"></a></p>

<!-- BEGIN: PROJECT LOADER -->
<!-- ALL THE PROJECT DETAILS WILL BE LOADED IN THIS AREA -->
<div class="projects-overlay overlay-contentpush">
    <div id="projects-loader"></div>
    <div class="projects-overlay-content">
        <div id="pagecontent" class="container">
            <div class="pageXofY">
                <span class="pageX"></span> / <span class="ofY"></span>
            </div>
            <div class="scrollbar">
                <div class="track">
                    <div class="thumb">
                        <div class="end"></div>
                    </div>
                </div>
            </div>
            <div class="viewport">
                <div class="overview">
                    <div id="pageloader" class="container">
                        <!-- THE LOADED CONTENT WILL SHOW HERE -->
                    </div>
                </div>
            </div>
        </div>
        <button type="button" class="overlay-close">Close</button>
        <nav class="projects-navigation">
            <div class="prev-proj">
                <a href="javascript:;">prev</a>
            </div>
            <div class="next-proj">
                <a href="javascript:;">next</a>
            </div>
        </nav>
    </div>
</div>
<!-- END -->

<!-- LOAD OTHER SCRIPTS -->
<script src="assets/js/paris.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/typed.js" type="text/javascript"></script>
<script>
    var k = 0;
    var techs = [];
    var pAndC;
    var nodejsStrings = [];
    var angularjsStrings = [];
    var meteorjsStrings = [];
    var knockoutjsStrings = [];
    var ionicStrings = [];
    var androidStrings = [];
    var iosString = [];
    var newStrings = [];
    var Titanium = [];
    var index = -1;
    var counter = 0;
    var proj_counter = 0;

    Constants = {
        Client_counter_Speed: 150,
        Project_counter_Speed: 150,    // Speed of counter on left and right side
        Typing_Speed: 50,
        Number_of_Slides: 6         // Total number of slides  in slider
    }


    $.ajax({
        dataType: "json",
        url: "datajson.php",
        data: k,
        success: function (params) {
            techs = params.technologies;
            pAndC = params.projectAndClient;
            nodejsStrings = params.nodejsStrings;
            angularjsStrings = params.angularjsStrings;
            meteorjsStrings = params.meteorjsStrings;
            knockoutjsStrings = params.knockoutjsStrings;
            ionicStrings = params.ionicStrings;
            androidStrings = params.androidStrings;
            iosString = params.iosString;
            Titanium = params.Titanium;
            newStrings = params.newStrings;
            index = -1;
            newTyped();
        }
    });


    function newTyped() {
        index++;
        if (index > Constants.Number_of_Slides) {
            index = 0;
        }

        var tech = techs[index];
        switch (tech) {
            case 'NodeJS':
                newStrings = nodejsStrings;
                break;
            case 'AngularJS':
                newStrings = angularjsStrings;
                break;
            case 'MeteorJS':
                newStrings = meteorjsStrings;
                break;
            case 'KnockouJS':
                newStrings = knockoutjsStrings;
                break;
            case 'Ionic':
                newStrings = ionicStrings;
                break;
            case 'Android':
                newStrings = androidStrings;
                break;
            case 'Ios':
                newStrings = iosString;
                break;
            case 'Titanium' :
                newStrings = Titanium;
                break;
        }
        $(".logo-wrap").find("." + tech).fadeIn(10);

        function proje_counter() {

            setTimeout(function projcounter() {
                if (proj_counter <= pAndC[tech].projects) {
                    var str = '';
                    if (proj_counter < 10) {
                        str += '0';
                    } else {
                        str += '';
                    }
                    $(".Project-figure").text(str + proj_counter).fadeIn(10);
                    proj_counter++;
                    proje_counter();
                }
                else {
                    proj_counter = 0;
                    return false;
                }

            }, Constants.Client_counter_Speed);
        }

        // $(".client-figure").text(pAndC[tech].clients);
        function client_counter() {

            setTimeout(function clientcounter() {
                if (counter <= pAndC[tech].clients) {
                    var str = '';
                    if (counter < 10) {
                        str += '0';
                    } else {
                        str += '';
                    }
                    $(".client-figure").text(str + counter).fadeIn(500);
                    ;
                    counter++;
                    client_counter();
                }
                else {
                    counter = 0;
                    return false;
                }

            }, Constants.Project_counter_Speed);
        }

        client_counter();
        proje_counter();

        //   console.log( "pac" , pAndC[tech].clients );
        //  $(".Project-figure").text(pAndC[tech].projects).fadeIn(500);
        $("#" + tech).fadeIn(500);
        $("#tags").text(pAndC[tech].Taglines);

        $("#typed").typed({
            strings: newStrings,
            typeSpeed: Constants.Typing_Speed,   // 50
            backDelay: 500,   // 500
            loop: false,
            contentType: 'html', // or text
            // defaults to false for infinite loop
            loopCount: false,
            callback: function () {
                nextTech();
            },
            resetCallback: function () {
                $(".logo-wrap").find(".img-responsive").fadeOut(500);
                $("#" + tech).fadeOut(500);
                $("#typed").fadeOut(500);
                $(".logo-list").fadeOut(500);
                //$(".client-figure").fadeOut(500);
                //$(".Project-figure").fadeOut(500);
                setTimeout(function () {
                    newTyped();
                }, 1000);
            }
        }).fadeIn(1000);
    }

    function nextTech() {
        setTimeout(function () {
            $("#typed").typed('reset');
        }, 500);
    }


</script>
<script>
    //$('.quick-form').css('display', 'none');
    $(document).ready(function () {
        $('#fetr-wrk1').addClass('importantRule');

        $('.show-me').click(function () {
            if ($('.quick-contact').hasClass('noView')) {
                $('.quick-contact').animate({'right': 0}, 300).removeClass('noView');
                $('.show-me > .fa').addClass('turn-me');
                $('.show-me').addClass('change-me');
            } else {
                $('.quick-contact').animate({'right': '-300px'}, 300).addClass('noView');
                $('.show-me > .fa').removeClass('turn-me');
                $('.show-me').removeClass('change-me');
            }
            ;
        });
    });
</script>
<script>
    function validate() {

        var name = document.mainform.name.value;
        if (!isNaN(name)) {
            alert("Please Enter Only Characters");
            document.mainform.name.focus();
            return false;
        }

        var emailID = document.mainform.email.value;

        atpos = emailID.indexOf("@");
        dotpos = emailID.lastIndexOf(".");
        if (atpos < 1 || ( dotpos - atpos < 2 )) {
            alert("Please enter correct email ID")
            document.mainform.email.focus();
            return false;
        }

        var val = document.mainform.contact.value;
        if (/^\d{10}$/.test(val)) {
            // value is ok, use it
        } else {
            alert("Invalid number; must be ten digits")
            document.mainform.contact.focus();
            return false;
        }
    }
</script>

</body>
</html>